current_profile: "default"
profiles:
  default:
    source_base_url: "https://source-jira.example.com"
    target_base_url: "https://target-jira.example.com"
    identity_mapping_file: "./examples/identity-mapping.sample.csv"
    identity_mapping_set: "true"
    teams_file: ""
    persons_file: ""
    resources_file: ""
    issues_csv: "./examples/issues.sample.csv"
    filter_source_csv: "./examples/filter-source.sample.csv"
    output_dir: "./out"
    team_scope: "all"
    issue_project_scope: "MIG,CORE"
    filter_team_ids_in_scope: "true"
    filter_team_ids_in_scope_set: "true"
    parent_link_in_scope: "true"
    parent_link_in_scope_set: "true"
    filter_data_source: "db-csv"
    filter_scriptrunner_installed: "false"
    filter_scriptrunner_endpoint: ""
